import { GirlProfile, LevelConfig, PlayerSkin, WeaponItem } from './types';

export const GIRLS_DATA: GirlProfile[] = [
  {
    id: 1,
    name: 'Sofía',
    tagline: 'La Vecina Gamer & Streamer',
    personality: 'Espontánea, fanática de los RPGs retro y amante de la pizza nocturna.',
    favGift: 'Mando retro dorado & Pizza familiar',
    color: '#38bdf8',
    accentColor: '#0284c7',
    avatarIcon: '🎮',
    roomTheme: 'Habitación gamer con luces LED RGB, pantallas triples, sillón puff y pósteres anime.',
    dialogueSuccess: [
      '¡Por fin llegaste a mi habitación! ¡Peleaste como un guerrero legendario!',
      '¡Justo a tiempo con la pizza antes de que empiece mi stream de Twitch!',
      '¡Esquivaste la chancla de mi papá en el pasillo! ¡Rango Diamante absoluto!'
    ],
    dialogueCaught: '¡Ufff! Mi papá salió del salón con la chancla supersónica...',
    secretFact: 'Tiene el récord mundial de velocidad en Mario Bros y entrena a su loro para imitar timbres.'
  },
  {
    id: 2,
    name: 'Valentina',
    tagline: 'La Capitana de Atletismo',
    personality: 'Competitiva, enérgica y adicta a los batidos de proteínas.',
    favGift: 'Zapatillas doradas de velocidad',
    color: '#f97316',
    accentColor: '#c2410c',
    avatarIcon: '🏃‍♀️',
    roomTheme: 'Dormitorio con trofeos, medallas relucientes, mancuernas de oro y zapatillas exclusivas.',
    dialogueSuccess: [
      '¡Qué reflejos para noquear a los robots aspiradora del salón!',
      '¡Mi papá estaba viendo el fútbol pero te le escapaste en la cocina!',
      '¡Toma un batido de victoria! Eres el más rápido de la cuadra.'
    ],
    dialogueCaught: '¡Mi papá fue lanzador de jabalina y la sandalia te interceptó en el pasillo!',
    secretFact: 'Suele hacer 200 flexiones antes de dormir para relajarse.'
  },
  {
    id: 3,
    name: 'Sakura',
    tagline: 'La Heredera del Dojo de Karate',
    personality: 'Seria pero de corazón dulce, amante del té boba y los gatitos.',
    favGift: 'Cinta dorada de artes marciales & Té boba',
    color: '#ec4899',
    accentColor: '#be185d',
    avatarIcon: '🥋',
    roomTheme: 'Habitación estilo japonés tradicional con suelo de tatami, bonsái centenario y biombos de seda.',
    dialogueSuccess: [
      'Tu técnica de combate con la almohada tiene una fluidez envidiable.',
      'Derrotaste a los muñecos de práctica y cruzaste el pasillo de madera sin hacer crujir las tablas.',
      'Acepto este regalo sagrado. Siéntate a tomar té antes de que mi padre patrulle de nuevo.'
    ],
    dialogueCaught: '¡El Gran Maestro sintió la vibración de tus pasos en el suelo de tatami!',
    secretFact: 'Por las noches ve comedias románticas a escondidas y llora de emoción con pañuelos.'
  },
  {
    id: 4,
    name: 'Chloe',
    tagline: 'La Ingeniera & Hacker Genio',
    personality: 'Hiperinteligente, sarcástica y creadora de robots traviesos.',
    favGift: 'Procesador cuántico & Flores holográficas',
    color: '#a855f7',
    accentColor: '#7e22ce',
    avatarIcon: '🤖',
    roomTheme: 'Laboratorio dormitorio futurista con monitores holográficos, robots en miniatura y bobinas tesla.',
    dialogueSuccess: [
      '¡Desactivaste mi sistema de robots de limpieza sin alertar las alarmas!',
      'Tienes un 99.8% de estilo en combate cuerpo a cuerpo.',
      'Conecta este chip para que la próxima vez las puertas se abran solas.'
    ],
    dialogueCaught: '¡Alerta roja de protocolo paterno! Los sensores infrarrojos activaron la chancla guiada...',
    secretFact: 'Construyó un dron robot con forma de gato que roba galletas de la cocina.'
  },
  {
    id: 5,
    name: 'Camila',
    tagline: 'La Influencer de Moda',
    personality: 'Glamorosa, divertida, siempre lista para un video viral.',
    favGift: 'Anillo de luz LED & Gafas de sol de diseño',
    color: '#eab308',
    accentColor: '#a16207',
    avatarIcon: '📸',
    roomTheme: 'Suite de lujo con vestidor gigante, luces cálidas, espejo de maquillaje y plantas tropicales.',
    dialogueSuccess: [
      '¡Ese combo de golpes a los gnomos del pasillo quedó brutal para mi vlog!',
      '¡Tienes 100/10 en valentía para entrar a la casa con mi papá merodeando!',
      '¡Una selfie rápida antes de que suene la campana de la cena!'
    ],
    dialogueCaught: '¡Papá apareció en cámara con la toalla del baño y la chancla voladora! ¡Corte!',
    secretFact: 'Sabe hablar 4 idiomas y finge que no le gusta el reguetón clásico.'
  },
  {
    id: 6,
    name: 'Luna',
    tagline: 'La Poeta Gótica & Mística',
    personality: 'Misteriosa, fanática de la astrología, gatos negros y la noche.',
    favGift: 'Rosa negra de terciopelo & Cuarzo lunar',
    color: '#6366f1',
    accentColor: '#4338ca',
    avatarIcon: '🌙',
    roomTheme: 'Dormitorio gótico victoriano con candelabros, estanterías repletas de grimorios y tapices púrpuras.',
    dialogueSuccess: [
      'Las cartas del tarot profetizaron tu llegada victoriosa a mis aposentos.',
      'Venciste a los murciélagos traviesos y burlaste a mi madre con su rodillo.',
      'Toma este amuleto protector para tu camino de regreso por la casa.'
    ],
    dialogueCaught: '¡Los espíritus de la casa alertaron a mi abuela con su zapatilla maldita!',
    secretFact: 'Su habitación tiene una puerta secreta que da directamente a la heladería del barrio.'
  },
  {
    id: 7,
    name: 'Isabella',
    tagline: 'La Vocalista de Pop-Rock',
    personality: 'Eléctrica, apasionada, vive con la música al máximo volumen.',
    favGift: 'Micrófono de cristal & Púa dorada',
    color: '#f43f5e',
    accentColor: '#be123c',
    avatarIcon: '🎸',
    roomTheme: 'Ático insonorizado con guitarras eléctricas colgadas, amplificadores Marshall y discos de platino.',
    dialogueSuccess: [
      '¡Tu entrada derribando a los monstruos del pasillo fue un solo de guitarra brutal!',
      '¡El público ruge! Y por público me refiero a mi perro que te vio pasar.',
      '¡Fírmame el autógrafo y quédate a escuchar mi nueva balada rock!'
    ],
    dialogueCaught: '¡Mi padre bajó los plomos de la luz y lanzó la zapatilla como un boomerang!',
    secretFact: 'Compuso su primer éxito musical usando cucharas de madera y cacerolas de la cocina.'
  },
  {
    id: 8,
    name: 'Mia',
    tagline: 'La Maestra Pastelera',
    personality: 'Dulce, risueña, creadora de los postres más deliciosos del país.',
    favGift: 'Fresas gigantes con chocolate & Molde de oro',
    color: '#fb7185',
    accentColor: '#e11d48',
    avatarIcon: '🧁',
    roomTheme: 'Buhardilla aromática a vainilla, con cajas de macarons, guirnaldas de galletas y horno portátil.',
    dialogueSuccess: [
      '¡Llegaste a mi habitación sin romper ni un solo pastelito de la vitrina!',
      'Toma un croissant caliente recién horneado como premio a tu combate épico.',
      'Mi mamá estaba en la cocina amasando, ¡pero fuiste más sigiloso que un ratoncito!'
    ],
    dialogueCaught: '¡Mi madre sintió tus pasos en la masa de pan y salió con el rodillo supremo!',
    secretFact: 'Puede adivinar el postre favorito de una persona con solo mirarle los zapatos.'
  },
  {
    id: 9,
    name: 'Elena',
    tagline: 'La Astrónoma & Soñadora Espacial',
    personality: 'Curiosa, metódica y fascinada por los cometas y constelaciones.',
    favGift: 'Fragmento de meteorito brillante & Globo estelar',
    color: '#06b6d4',
    accentColor: '#0e7490',
    avatarIcon: '🔭',
    roomTheme: 'Cúpula en el tejado con telescopio gigante, proyector de galaxias en el techo y mapas estelares.',
    dialogueSuccess: [
      '¡Tu trayectoria a través de los salones esquivó a todos los obstáculos con precisión orbital!',
      '¡Te vi avanzar por el reflejo del espejo del telescopio!',
      'Ven a mirar los anillos de Saturno antes de que Papá termine de patrullar el vestíbulo.'
    ],
    dialogueCaught: '¡Mi papá calculó la trayectoria parabólica de la chancla con ecuaciones de la NASA!',
    secretFact: 'Descubrió un asteroide nuevo y lo bautizó con el nombre de su perro salchicha.'
  },
  {
    id: 10,
    name: 'Valeria',
    tagline: 'La Princesa de la Gran Mansión',
    personality: 'Orgullosa, audaz y protectora de su propia torre inexpugnable.',
    favGift: 'Corona de rosas de diamante & Carta de amor definitiva',
    color: '#8b5cf6',
    accentColor: '#6d28d9',
    avatarIcon: '👑',
    roomTheme: 'Suite presidencial en la última planta con vidrieras, alfombra roja real, cama con dosel y terraza privada.',
    dialogueSuccess: [
      '¡INCREÍBLE! ¡Derrotaste a todos los guardianes de la mansión y llegaste a mi alcoba!',
      '¡Venciste la furia combinada de mi Papá y mi Mamá en el gran salón!',
      '¡Eres el verdadero Campeón del Amor! ¡Una leyenda absoluta!'
    ],
    dialogueCaught: '¡Activaron la Chancla Titán y el Rodillo Supremo en tándem! ¡Nadie escapa de ambos!',
    secretFact: 'Diseñó el laberinto de habitaciones para asegurarse de que solo el pretendiente más valiente llegara.'
  }
];

export const LEVELS_CONFIG: LevelConfig[] = [
  {
    id: 1,
    title: 'Nivel 1: La Casa de Sofía',
    subtitle: 'Salón acogedor y pasillo con gnomos traviesos',
    difficulty: 'Fácil',
    girlId: 1,
    houseTheme: 'suburban',
    floorColor: 0x854d0e, // Warm wood parquet
    wallColor: 0xfef3c7,  // Soft cream
    carpetColor: 0xd97706,
    accentLightColor: 0xfbbf24,
    description: 'Avanza por el salón de Sofía. Derrota a los gnomos que custodian el televisor y llega a su habitación gamer.',
    parTime: 40,
    parentType: 'dad_slipper',
    parentSpeed: 2.8,
    parentPatrolRadius: 4.5,
    enemyTypes: ['gnome'],
    enemyCount: 3,
    furnitureStyle: 'cozy'
  },
  {
    id: 2,
    title: 'Nivel 2: El Loft de Valentina',
    subtitle: 'Piso de parquet moderno y robots aspiradora veloces',
    difficulty: 'Fácil',
    girlId: 2,
    houseTheme: 'modern',
    floorColor: 0x78716c,
    wallColor: 0xf8fafc,
    carpetColor: 0xf97316,
    accentLightColor: 0xfb923c,
    description: 'Cruza la sala de entrenamiento de Valentina. Golpea a los robots de limpieza descontrolados y esquiva a Papá.',
    parTime: 45,
    parentType: 'dad_slipper',
    parentSpeed: 3.2,
    parentPatrolRadius: 5.0,
    enemyTypes: ['vacuum_robot', 'dust_bunny'],
    enemyCount: 4,
    furnitureStyle: 'sleek'
  },
  {
    id: 3,
    title: 'Nivel 3: El Dojo Residencial de Sakura',
    subtitle: 'Suelo de tatami, biombos y gatos ninja guardianes',
    difficulty: 'Media',
    girlId: 3,
    houseTheme: 'dojo',
    floorColor: 0xd97706, // Tatami straw color
    wallColor: 0xffedd5,
    carpetColor: 0xdc2626,
    accentLightColor: 0xf43f5e,
    description: 'Camina con sigilo por la casa tradicional. Pelea con los gatos traviesos sin despertar al Gran Maestro.',
    parTime: 50,
    parentType: 'dad_slipper',
    parentSpeed: 3.4,
    parentPatrolRadius: 5.5,
    enemyTypes: ['laser_cat', 'dust_bunny'],
    enemyCount: 5,
    furnitureStyle: 'traditional'
  },
  {
    id: 4,
    title: 'Nivel 4: La Casa Inteligente de Chloe',
    subtitle: 'Suelo de cuarzo blanco, luces LED y robots de seguridad',
    difficulty: 'Media',
    girlId: 4,
    houseTheme: 'cyberpunk',
    floorColor: 0x0f172a,
    wallColor: 0x1e293b,
    carpetColor: 0xa855f7,
    accentLightColor: 0x38bdf8,
    description: 'Hackea tu paso derribando a los robots patrulla y entra a la habitación tecnológica de Chloe.',
    parTime: 55,
    parentType: 'dad_slipper',
    parentSpeed: 3.6,
    parentPatrolRadius: 6.0,
    enemyTypes: ['vacuum_robot', 'laser_cat'],
    enemyCount: 5,
    furnitureStyle: 'tech'
  },
  {
    id: 5,
    title: 'Nivel 5: La Villa de Playa de Camila',
    subtitle: 'Mármol brillante, palmeras interiores y sofás dorados',
    difficulty: 'Media',
    girlId: 5,
    houseTheme: 'tropical',
    floorColor: 0xfef08a,
    wallColor: 0xfffbeb,
    carpetColor: 0xeab308,
    accentLightColor: 0xfacc15,
    description: 'Una mansión espaciosa llena de gnomos y pelusas. Llega a la suite de Camila antes de que empiece su directo.',
    parTime: 55,
    parentType: 'dad_slipper',
    parentSpeed: 3.8,
    parentPatrolRadius: 6.0,
    enemyTypes: ['gnome', 'dust_bunny'],
    enemyCount: 6,
    furnitureStyle: 'luxury'
  },
  {
    id: 6,
    title: 'Nivel 6: La Mansión de Luna',
    subtitle: 'Candelabros, biblioteca victoriana y murciélagos juguetones',
    difficulty: 'Difícil',
    girlId: 6,
    houseTheme: 'gothic',
    floorColor: 0x18181b,
    wallColor: 0x27272a,
    carpetColor: 0x4f46e5,
    accentLightColor: 0x818cf8,
    description: 'Una casa antigua y misteriosa. Mamá patrulla con su rodillo mientras murciélagos intentan asustarte.',
    parTime: 60,
    parentType: 'mom_pin',
    parentSpeed: 3.8,
    parentPatrolRadius: 6.5,
    enemyTypes: ['mischief_bat', 'dust_bunny'],
    enemyCount: 6,
    furnitureStyle: 'vintage'
  },
  {
    id: 7,
    title: 'Nivel 7: El Ático Musical de Isabella',
    subtitle: 'Suelos oscuros, alfombras de terciopelo y amplificadores',
    difficulty: 'Difícil',
    girlId: 7,
    houseTheme: 'highrise',
    floorColor: 0x262626,
    wallColor: 0x404040,
    carpetColor: 0xe11d48,
    accentLightColor: 0xf43f5e,
    description: 'Ábrete paso por el salón de música noqueando a los robots y gatos para entrar al estudio de Isabella.',
    parTime: 60,
    parentType: 'dad_slipper',
    parentSpeed: 4.0,
    parentPatrolRadius: 6.5,
    enemyTypes: ['vacuum_robot', 'laser_cat', 'gnome'],
    enemyCount: 7,
    furnitureStyle: 'sleek'
  },
  {
    id: 8,
    title: 'Nivel 8: La Casa Dulce de Mia',
    subtitle: 'Cocina espaciosa, nubes de azúcar y gnomos golosos',
    difficulty: 'Difícil',
    girlId: 8,
    houseTheme: 'bakery',
    floorColor: 0xfde047,
    wallColor: 0xfefce8,
    carpetColor: 0xf43f5e,
    accentLightColor: 0xfb7185,
    description: 'La casa de la panadera huele a vainilla pero está custodiada por gnomos golosos y Mamá con el rodillo.',
    parTime: 65,
    parentType: 'mom_pin',
    parentSpeed: 4.2,
    parentPatrolRadius: 7.0,
    enemyTypes: ['gnome', 'dust_bunny'],
    enemyCount: 7,
    furnitureStyle: 'cozy'
  },
  {
    id: 9,
    title: 'Nivel 9: La Residencia Astronómica de Elena',
    subtitle: 'Salas circulares, maquetas de planetas y telescopios',
    difficulty: 'Extrema',
    girlId: 9,
    houseTheme: 'observatory',
    floorColor: 0x0f172a,
    wallColor: 0x1e293b,
    carpetColor: 0x0284c7,
    accentLightColor: 0x38bdf8,
    description: 'Tanto Papá como Mamá vigilan el vestíbulo estelar. Usa cáscaras de plátano para despejar el camino.',
    parTime: 70,
    parentType: 'both',
    parentSpeed: 4.2,
    parentPatrolRadius: 7.5,
    enemyTypes: ['vacuum_robot', 'mischief_bat', 'laser_cat'],
    enemyCount: 8,
    furnitureStyle: 'tech'
  },
  {
    id: 10,
    title: 'Nivel 10: La Mansión Real de Valeria',
    subtitle: 'El Gran Salón del Trono y el pasillo de la alcoba real',
    difficulty: 'Extrema',
    girlId: 10,
    houseTheme: 'castle',
    floorColor: 0x450a0a,
    wallColor: 0x7f1d1d,
    carpetColor: 0xd97706,
    accentLightColor: 0xfbbf24,
    description: '¡El combate definitivo en la mansión! Papá y Mamá patrullan el salón con la Súper Chancla y el Rodillo.',
    parTime: 80,
    parentType: 'mega_dad',
    parentSpeed: 4.6,
    parentPatrolRadius: 8.5,
    enemyTypes: ['gnome', 'vacuum_robot', 'laser_cat', 'dust_bunny'],
    enemyCount: 10,
    furnitureStyle: 'royal'
  }
];

export const SKINS_DATA: PlayerSkin[] = [
  {
    id: 'default',
    name: 'Romeo Casual',
    desc: 'Sudadera roja clásica y zapatillas cómodas para entrar a escondidas.',
    cost: 0,
    unlocked: true,
    shirtColor: 0xef4444,
    pantsColor: 0x1e293b,
  },
  {
    id: 'ninja',
    name: 'Ninja Doméstico',
    desc: 'Traje oscuro de sigilo. Reduce el rango en que los padres y gnomos te escuchan.',
    cost: 150,
    unlocked: false,
    shirtColor: 0x18181b,
    pantsColor: 0x09090b,
    headExtra: 'ninja_mask',
  },
  {
    id: 'box',
    name: 'Caja Táctica Metal Box',
    desc: '¡Disfraz de caja de cartón! +25% de sigilo frente a la mirada de Papá.',
    cost: 250,
    unlocked: false,
    shirtColor: 0xb45309,
    pantsColor: 0x78350f,
    headExtra: 'box',
  },
  {
    id: 'tuxedo',
    name: 'Caballero Romántico',
    desc: 'Esmoquin elegante con solapa negra. Conquista con porte y distinción.',
    cost: 350,
    unlocked: false,
    shirtColor: 0x0f172a,
    pantsColor: 0x020617,
  },
  {
    id: 'bear',
    name: 'Pijama de Oso Cariñoso',
    desc: 'Acolchado suave. ¡Hace que los golpes de los gnomos reboten!',
    cost: 450,
    unlocked: false,
    shirtColor: 0xd97706,
    pantsColor: 0xb45309,
    headExtra: 'bear_ears',
  }
];

export const WEAPONS_DATA: WeaponItem[] = [
  {
    id: 'pillow',
    name: 'Mega Almohada de Plumas',
    desc: 'Golpea con combo rápido y suelta plumas que confunden a los enemigos.',
    cost: 0,
    unlocked: true,
    damage: 1,
    icon: '🛏️',
    modelType: 'pillow',
    glowColor: 0xf8fafc
  },
  {
    id: 'rose',
    name: 'Ramo de Rosas Látigo',
    desc: 'Mayor alcance y espinas afiladas para mantener a raya a los robots de limpieza.',
    cost: 120,
    unlocked: false,
    damage: 2,
    icon: '🌹',
    modelType: 'rose',
    glowColor: 0xef4444
  },
  {
    id: 'water_gun',
    name: 'Super Pistola de Agua',
    desc: 'Dispara ráfagas de agua que empujan y aturden a los enemigos a distancia.',
    cost: 220,
    unlocked: false,
    damage: 2,
    icon: '🔫',
    modelType: 'water_gun',
    glowColor: 0x06b6d4
  },
  {
    id: 'chancla_golden',
    name: 'La Chancla Dorada de Poder',
    desc: '¡El arma suprema de la casa! Aturde a cualquier padre o monstruo de un solo golpe.',
    cost: 500,
    unlocked: false,
    damage: 4,
    icon: '🩴',
    modelType: 'chancla_golden',
    glowColor: 0xfacc15
  }
];
